version: '3.5'
services:
  back:
    image: back # укажите тэг или id контейнера 
    container_name: back
    ports:
      - "8000:8000"
  
  front:
    image: front # укажите тэг или id контейнера
    container_name: front
    depends_on:
      - back
    ports:
      - "3000:3000"
  